version: ''
services: 
   api: 
      build: 
         context: ./client
      ports:
         - "3000:3000"
      expose:
      - 3000
      container_name: client
      volumes:
         - .:/client
   node-server:
      build:
         context: ./server
      ports:
         - "4047:4047"
      container_name: express 
      volumes:
        - .:/server